### ISSUE TITLE
using dev instance to teach bio.tools

### ISSUE THREAD

**Issue by mkuzak** [SoftDev4Research/4OSS-lesson#15]
bio.tools team has a dev server that we can use for training so that we don't flood the main bio.tools server
https://dev.bio.tools/

**Comment by fpsom** [comment]
@mkuzak that's not a bad idea. But we need to confirm with the bio.tools team that:
1. The entries there are indeed deleted at various points
2. A participant can login so that they create a new entry (or at least be able to create entries without login)
3. There is not going to be a problem with 30+ concurrent sessions accessing the dev platform.

**Comment by mkuzak** [comment]
I just talked to Jon Ison @joncison about it and this was suggested solution. We'll have to try it out to see how it works in practice.

**Comment by mkuzak** [comment]
the instance we should be able to use is https://dev.bio.tools

**Comment by fpsom** [comment]
I've added the new information in the PR. Unless there are objections, I will close the issue as soon as the PR is merged.

**Comment by fpsom** [comment]
Fixed in PR #52
