### ISSUE TITLE
REC1: This lesson should consider also people who do not or are not able to open source their code

### ISSUE THREAD

**Issue by wikfeldt** [SoftDev4Research/4OSS-lesson#2]
However, we should have a clear direction and recommendation. We can decide what it should be about and then either convince people or make them understand whether the workshop is appropriate for them or not.

**Comment by orchid00** [comment]
Hi @wikfeldt could you read two episodes. 1 [introduction](https://github.com/SoftDev4Research/4OSS-lesson/blob/gh-pages/_episodes/01-introduction.md) and 2 [make it public](https://github.com/SoftDev4Research/4OSS-lesson/blob/gh-pages/_episodes/02-make-it-public.md), please check that your suggestion has been addressed. If it hasn't then, could you point out where should this suggestion be added.

**Comment by wikfeldt** [comment]
Hi Paula, thanks for reaching out. I actually can't see much discussion catering to people who might have some reasons to keep some source code closed (at least initially), but I guess that's intentionally left out since the material is really about best practices in open source projects. My point about this was that the material should be inclusive to people who might want to close-source some of their projects for some amount of time, and to convey the message that good software development practices are equally important to such projects as well, but perhaps that's outside the scope of the material as it is now.

**Comment by orchid00** [comment]
I think it it is inclusive, but it will be worth adding that the recommendations can be also used on non-open projects.
Perhaps recommendation 1 "Make it public from the first day" instead of a public repository can be made as a private repository. Even non-open projects should have a version control flow, from there, license, contributions and metadata are valid recommendations too. What do you think? @wikfeldt 
I would leave out the part of the discussion on why open source or why not, and instead clarify that the recommendations are not exclusive.

**Comment by orchid00** [comment]
Hi @wikfeldt we added a little line about this in https://github.com/SoftDev4Research/4OSS-lesson/blob/gh-pages/_episodes/01-introduction.md

**Comment by orchid00** [comment]
this PR https://github.com/SoftDev4Research/4OSS-lesson/pull/90 closes this issue.
